### ISSUE TITLE
Generating barcode by destination for DE fails

### ISSUE THREAD

**Issue by Dybo** [DivideBV/Postnl#11]
When I try to create a barcode using the generateBarcodeByDestination function it fails when I want to create one for a address in Germany using the country code DE

The error I get is:

Validation failed for shipment: 3STTWJ196232075, Messages: Barcode length must be 13 characters

**Comment by ameenross** [comment]
Normally 3S barcodes may be 15 characters long, so the library requests 3S barcodes with serie `000000000-999999999` by default. If that doesn't work in your case (possibly because of some specific product code?) then override the `$serie` parameter of the function. https://github.com/DivideBV/Postnl/blob/master/src/Postnl.php#L221

**Comment by Dybo** [comment]
I am sorry I was looking at the wrong place it actually happens when I try to generate a label with a shipment that contains a 15 character long barcode. I still didn't fix it I don't know why it is failing with a 15 character long barcode.
- Fixed it by overriding the `$serie` parameter.
