### ISSUE TITLE
getShipments

### ISSUE THREAD

**Issue by LVoogd** [DivideBV/Postnl#20]
Hello,

I'm trying to retrieve the status codes of my shipments. Iam using the following code:

```
    $status = $client->currentStatus($barcode);
$shipments = $status->getShipments();
```

The response contains the data I want but I have no clue how to access it because it's protected. 
I think I somehow need to access ResponseStatus->getCurrentStatusCode but I dont know how..

 Any help would be appreciated!

**Comment by ameenross** [comment]
Yeah, CIF kinda buries information in a whole lot of apparently unnecessary wrappers. I can give you a code example that should work, but first I should point out that the classes that carry the data are using the accessor/mutator pattern. This means that the value of any `some_property` on an object can be gotten by `getSomeProperty()` method call. You'll have to call a couple in succession to drill down to the data you need, because CIF.

So without further ado, here's the example.

``` php
foreach ($result->getShipments() as $shipment) {
    if ($status = $shipment->getStatus()) {
        // Get ETA if it exists.
        $eta = '';
        if ($expectation = $shipment->getExpectation()) {
            $from = $expectation->getETAFrom();
            $to = $expectation->getETATo();
        }

        $phaseCode = $status->getCurrentPhaseCode();
        $phaseDescription = $status->getCurrentPhaseDescription();
        $statusCode = $status->getCurrentStatusCode();
        $statusDescription = $status->getCurrentStatusDescription();
        $statusTimestamp = $status->getCurrentStatusTimeStamp();
    }
}
```

**Comment by LVoogd** [comment]
Ah thanks, everything is starting to make alot more sense now.
