### ISSUE TITLE
Ability to call client functions not wrapped in main class

### ISSUE THREAD

**Issue by tomhooijenga** [DivideBV/Postnl#36]
In the Postnl class, there are setters to set the various clients. However, there are no getters for them. Because of this, there is no easy way to call some parts of the api. (For example, completeStatus from ShippingStatusClient).
Two possible fixes: Proxy all methods from each client in the Postnl class, or make the clients themselves accessible.

**Comment by ameenross** [comment]
Actually, there's [getClient](https://github.com/DivideBV/Postnl/blob/master/src/Postnl.php#L533). It's just protected is all. I have considered making it public in the past, but decided not to, because I figured the main class might only be an obstacle for a developer with more custom needs.

I don't think proxying all methods is a good idea, unless the wrapper function actually adds value (which is the case for the functions currently in there). Making the `getClient` function public is probably the best solution.

**Comment by tomhooijenga** [comment]
I think it it is more convenient to have the getClient method public. That way, there is a single access point to the api. This also prevents the consumer from dealing with the SecurityHeader. Are there any downsides in doing this?

**Comment by ameenross** [comment]
> Are there any downsides in doing this?

Probably only psychological. In other words, no :)

**Comment by ameenross** [comment]
On second thought, that would result in code like this (and wouldn't catch CIF exceptions):

``` php
$request = new ComplexTypes\CompleteStatusRequest($message, $customer, $shipment);

// Query the webservice and return the result.
return $postnl->getClient('ShippingStatusClient')->completeStatus($request);
```

Making the `call` method available would be preferable, and using that will result in something like this (AND have proper CIF error handling):

``` php
$request = new ComplexTypes\CompleteStatusRequest($message, $customer, $shipment);

// Query the webservice and return the result.
return $postnl->call('ShippingStatusClient', 'completeStatus', $request);
```

If you agree then I'll patch it.

**Comment by tomhooijenga** [comment]
That is probably better. Great work!
