### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by slokhorst** [DivideBV/Postnl#5]
`README.md` says: requires PHP >= 5.4.
`composer.json` however says: requires `"php": "^5.4"`, which excludes PHP 7 (see [doc](https://getcomposer.org/doc/articles/versions.md#caret)).

I've briefly tested this on PHP 7.0, and everything seems to be working fine. I suggest you change the line in `composer.json` to `"php": ">=5.4"`.

**Comment by ameenross** [comment]
That caret was intentional. As for the readme, that's why I'm not a fan of listing dependencies in the readme. Packagist displays dependencies nicely, taken from `composer.json`. Now I need to update the dependencies both in the readme and in composer.

Also, I'd rather include PHP 7 after properly testing it myself. I'll see if I can do that later this year :smile:

**Comment by slokhorst** [comment]
Yes you're right.. Listing the dependencies in the readme is not really necessary, now `composer.json` contains all requirements.
The funny thing about Composer is that if I now install `dividebv/postnl`, it will grab `0.4.0`, because it thinks that that version _is_ compatible with PHP 7.

Anyway, no reason to rush things, better to properly test it. Thanks for your reply! :smile:

**Comment by ameenross** [comment]
Just tested a couple of clients' services and they all work without issues. I guess I could update the `composer.json` to indicate it works on PHP7. However, it's a potential extra support burden. I think I'm gonna take the risk, as there are not many backward compatibility breaking changes to the syntax in PHP7.
