### ISSUE TITLE
How to get the string of an openingshour

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [DivideBV/Postnl#53]
When i do:

$location->getName() on the ResponseLocation class it works. I get a string in return.

But when i do:

`$location->getOpeningHours()->getMonday() `

I get:

`stdClass Object ( [string] => 08:00-18:30 ) 1`

Sorry for the newbie question, but how do i get just the string in return?

I dont understand why it is not a string:

```
    /**
     * @return string
     */
    public function getMonday()
    {
        return $this->Monday;
    }


```

**Comment by ameenross** [comment]
My reasoning for not using it is that it's unsafe to throw in arbitrary user input for an entire address to PostNL. A safer approach is used in almost all webshops or logistic systems. Either one of

- have separate fields for street, housenumber and ext
- just allow entering postal code and house number, use some service to get the corresponding street (shown to the user as a sanity check), and a field for the ext. A fallback to the above approached may be used when a postal code service is not available

**Comment by ameenross** [comment]
My reasoning for not using it is that it's unsafe to throw in arbitrary user input for an entire address to PostNL. A safer approach is used in almost all webshops or logistic systems. Either one of

- have separate fields for street, housenumber and ext
- just allow entering postal code and house number, use some service to get the corresponding street (shown to the user as a sanity check), and a field for the ext. A fallback to the above approach may be used when a postal code service is not available

**Comment by ameenross** [comment]
(sorry for the noise, posted a reply here to another issue)

It seems to be due to the serialization PostNL uses. https://developer.postnl.nl/apis/location-webservice/documentation

It seems to support it being an array (probably to allow for, let's say, `8:00-12:00, 12:30-16:30`). You can do `$location->getOpeningHours()->getMonday()->string`, but it's not very developer friendly, and there's a discrepancy between the documentation and the code. I'm not sure how to improve this, as the result could be an array. If anyone knows whether this happens in practice, please share the knowledge
